%NUFFT2D3F90 - 
%
% Syntax:  [fk, ier] = nufft2d3f90(xj, yj, cj, iflag, eps, sk, tk)
%
% Inputs:
%    xj - double (nj,1)
%    yj - double (nj,1)
%    cj - double (nj,1)
%    iflag - int
%    eps - double
%    sk - int (nk,1)
%    tk - int (nk,1)
%
% Outputs:
%    fk - double (nk,1)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
