%NUFFT3D3F90 - 
%
% Syntax:  [fk, ier] = nufft3d3f90(xj, yj, zj, cj, iflag, eps, sk, tk, uk)
%
% Inputs:
%    xj - double (nj,1)
%    yj - double (nj,1)
%    zj - double (nj,1)
%    cj - double (nj,1)
%    iflag - int
%    eps - double
%    sk - int (nk,1)
%    tk - int (nk,1)
%    uk - int (nk,1)
%
% Outputs:
%    fk - double (1,nk)
%    ier - int (1,1)
%
% Auto-generated by mcwrap: https://github.com/magland/mcwrap
